
name: 'dbt_infer_examples'
version: "1.0"
config-version: 2
profile: 'dbt_infer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: 
  - "target"
  - "dbt_packages"

# we define 2018-09-04 to be today's date
vars:
  year: 2018
  month: 9
  day: 4

